### ISSUE TITLE
Delete copyright

### ISSUE THREAD

**Issue by MattNot** [MattNot/Curses-Bird#2]
Delete copyright string on this file:
https://github.com/MattNot/Curses-Bird/blob/master/src/logo.cpp

**Comment by iatharva** [comment]
I can do this.

We need to remove the below line present in the file right?
Please assign the issue to me, so I can start working on it.

``mvprintw(LINES/2, COLS/2, "\n Curses Bird  Copyright (C) 2018  Matteo Notaro \n This program comes with ABSOLUTELY NO WARRANTY; \n This is free software, and you are welcome to redistribute it \n under certain conditions; see \"LICENSE\" file for details \n github: MattNot \n LinkedIn: matteo-notaro \n For info you can write me on linkedin or create a issue on github.");`

**Comment by MattNot** [comment]
Hi, @Alerika already worked on it, thanks!
